import { colors } from "./colors.ts";
import packageJson from "./package.json" with { type: "json" };

export const vscodeThemeDark = {
  $schema: "vscode://schemas/color-theme",
  name: `${packageJson.name} Dark`,
  colors: {
    "focusBorder": colors.purple[1],
    "foreground": colors.ink[3],
    "disabledForeground": colors.ink[0],
    "widget.shadow": "#00000060",
    "selection.background": colors.glow[3],
    "descriptionForeground": colors.ink[3],
    "errorForeground": colors.orange[1],
    "icon.foreground": colors.purple[1],
    "sash.hoverBorder": colors.purple[1],
    "textBlockQuote.background": colors.canvas[1],
    "textBlockQuote.border": colors.canvas[2],
    "textCodeBlock.background": colors.canvas[1],
    "textLink.activeForeground": colors.blue[2],
    "textLink.foreground": colors.blue[1],
    "textPreformat.foreground": colors.ink[3],
    "textSeparator.foreground": colors.purple[1],
    "activityBar.background": colors.canvas[2],
    "activityBar.foreground": colors.purple[2],
    "activityBar.dropBorder": colors.glow[0],
    "activityBar.inactiveForeground": colors.ink[1],
    "activityBar.border": colors.canvas[4],
    "activityBarBadge.background": colors.purple[1],
    "activityBarBadge.foreground": colors.canvas[0],
    "activityBar.activeBorder": "#00000000",
    "activityBar.activeBackground": "#00000000",
    "activityBar.activeFocusBorder": "#00000000",
    "activityBarTop.foreground": colors.purple[1],
    "activityBarTop.activeBorder": "#00000000",
    "activityBarTop.inactiveForeground": colors.ink[1],
    "activityBarTop.dropBorder": colors.glow[0],
    "badge.background": colors.glow[1],
    "badge.foreground": colors.ink[3],
    "breadcrumb.activeSelectionForeground": colors.purple[1],
    "breadcrumb.background": colors.canvas[0],
    "breadcrumb.focusForeground": colors.purple[1],
    "breadcrumb.foreground": colors.ink[2],
    "breadcrumbPicker.background": colors.canvas[1],
    "button.background": colors.purple[1],
    "button.foreground": colors.canvas[0],
    "button.border": "#00000000",
    "button.separator": "#00000000",
    "button.hoverBackground": colors.purple[2],
    "button.secondaryForeground": colors.ink[3],
    "button.secondaryBackground": colors.glow[0],
    "button.secondaryHoverBackground": colors.glow[1],
    "checkbox.background": colors.glow[0],
    "checkbox.border": colors.canvas[3],
    "checkbox.foreground": colors.purple[1],
    "dropdown.background": colors.canvas[1],
    "dropdown.listBackground": colors.canvas[2],
    "dropdown.border": colors.purple[1],
    "dropdown.foreground": colors.ink[3],
    "debugToolBar.background": colors.canvas[2],
    "debugToolBar.border": "#00000000",
    "debugExceptionWidget.background": colors.canvas[2],
    "debugExceptionWidget.border": colors.purple[1],
    "debugTokenExpression.number": colors.orange[1],
    "debugTokenExpression.boolean": colors.purple[1],
    "debugTokenExpression.string": colors.green[1],
    "debugTokenExpression.error": colors.orange[1],
    "debugIcon.breakpointForeground": colors.orange[1],
    "debugIcon.breakpointDisabledForeground": "#f38ba899",
    "debugIcon.breakpointUnverifiedForeground": "#a6738c",
    "debugIcon.breakpointCurrentStackframeForeground": colors.canvas[3],
    "debugIcon.breakpointStackframeForeground": colors.canvas[3],
    "debugIcon.startForeground": colors.green[1],
    "debugIcon.pauseForeground": colors.blue[1],
    "debugIcon.stopForeground": colors.orange[1],
    "debugIcon.disconnectForeground": colors.canvas[3],
    "debugIcon.restartForeground": colors.cyan[1],
    "debugIcon.stepOverForeground": colors.purple[1],
    "debugIcon.stepIntoForeground": colors.ink[3],
    "debugIcon.stepOutForeground": colors.ink[3],
    "debugIcon.continueForeground": colors.green[1],
    "debugIcon.stepBackForeground": colors.canvas[3],
    "debugConsole.infoForeground": colors.blue[1],
    "debugConsole.warningForeground": colors.orange[1],
    "debugConsole.errorForeground": colors.orange[1],
    "debugConsole.sourceForeground": colors.yellow[2],
    "debugConsoleInputIcon.foreground": colors.ink[3],
    "testing.runAction": colors.purple[1],
    "testing.iconErrored": colors.orange[1],
    "testing.iconFailed": colors.orange[1],
    "testing.iconPassed": colors.green[1],
    "testing.iconQueued": colors.blue[1],
    "testing.iconUnset": colors.ink[3],
    "testing.iconSkipped": colors.ink[0],
    "testing.iconErrored.retired": colors.orange[1],
    "testing.iconFailed.retired": colors.orange[1],
    "testing.iconPassed.retired": colors.green[1],
    "testing.iconQueued.retired": colors.blue[1],
    "testing.iconUnset.retired": colors.ink[3],
    "testing.iconSkipped.retired": colors.ink[0],
    "testing.peekBorder": colors.purple[1],
    "testing.peekHeaderBackground": colors.canvas[2],
    "testing.message.error.lineBackground": "#f38ba826",
    "testing.message.info.decorationForeground": "#a6e3a1cc",
    "testing.message.info.lineBackground": "#a6e3a126",
    "testing.messagePeekBorder": colors.purple[1],
    "testing.messagePeekHeaderBackground": colors.canvas[3],
    "testing.coveredBackground": "#a6e3a14d",
    "testing.coveredBorder": "#00000000",
    "testing.coveredGutterBackground": "#a6e3a14d",
    "testing.uncoveredBranchBackground": "#f38ba833",
    "testing.uncoveredBackground": "#f38ba833",
    "testing.uncoveredBorder": "#00000000",
    "testing.uncoveredGutterBackground": "#f38ba840",
    "testing.coverCountBadgeBackground": "#00000000",
    "testing.coverCountBadgeForeground": colors.purple[1],
    "diffEditor.border": colors.canvas[3],
    "diffEditor.insertedTextBackground": "#a6e3a133",
    "diffEditor.removedTextBackground": "#f38ba833",
    "diffEditor.insertedLineBackground": "#a6e3a126",
    "diffEditor.removedLineBackground": "#f38ba826",
    "diffEditor.diagonalFill": "#585b7099",
    "diffEditorOverview.insertedForeground": "#a6e3a1cc",
    "diffEditorOverview.removedForeground": "#f38ba8cc",
    "editor.background": colors.canvas[0],
    "editor.findMatchBackground": "#5e3f53",
    "editor.findMatchBorder": "#f38ba833",
    "editor.findMatchHighlightBackground": "#3e5767",
    "editor.findMatchHighlightBorder": "#89dceb33",
    "editor.findRangeHighlightBackground": "#3e5767",
    "editor.findRangeHighlightBorder": "#89dceb33",
    "editor.foldBackground": "#89dceb40",
    "editor.foreground": colors.ink[3],
    "editor.hoverHighlightBackground": "#89dceb40",
    "editor.lineHighlightBackground": "#cdd6f412",
    "editor.lineHighlightBorder": "#00000000",
    "editor.rangeHighlightBackground": "#89dceb40",
    "editor.rangeHighlightBorder": "#00000000",
    "editor.selectionBackground": "#9399b240",
    "editor.selectionHighlightBackground": "#9399b233",
    "editor.selectionHighlightBorder": "#9399b233",
    "editor.wordHighlightBackground": "#9399b233",
    "editor.wordHighlightStrongBackground": "#89b4fa33",
    "editorBracketMatch.background": colors.glow[4],
    "editorBracketMatch.border": colors.ink[2],
    "editorCodeLens.foreground": colors.ink[0],
    "editorCursor.background": colors.canvas[0],
    "editorCursor.foreground": colors.yellow[2],
    "editorGroup.border": colors.canvas[3],
    "editorGroup.dropBackground": colors.glow[0],
    "editorGroup.emptyBackground": colors.canvas[0],
    "editorGroupHeader.tabsBackground": colors.canvas[2],
    "editorGutter.addedBackground": colors.green[1],
    "editorGutter.background": colors.canvas[0],
    "editorGutter.commentRangeForeground": colors.glow[0],
    "editorGutter.commentGlyphForeground": colors.purple[1],
    "editorGutter.deletedBackground": colors.orange[1],
    "editorGutter.foldingControlForeground": colors.ink[2],
    "editorGutter.modifiedBackground": colors.yellow[1],
    "editorHoverWidget.background": colors.canvas[1],
    "editorHoverWidget.border": colors.canvas[3],
    "editorHoverWidget.foreground": colors.ink[3],
    "editorIndentGuide.activeBackground": colors.glow[4],
    "editorIndentGuide.background": colors.glow[2],
    "editorInlayHint.foreground": colors.ink[1],
    "editorInlayHint.background": colors.glow[0],
    "editorInlayHint.typeForeground": colors.ink[2],
    "editorInlayHint.typeBackground": colors.glow[0],
    "editorInlayHint.parameterForeground": colors.ink[0],
    "editorInlayHint.parameterBackground": colors.glow[0],
    "editorLineNumber.activeForeground": colors.purple[1],
    "editorLineNumber.foreground": colors.ink[0],
    "editorLink.activeForeground": colors.purple[1],
    "editorMarkerNavigation.background": colors.canvas[1],
    "editorMarkerNavigationError.background": colors.orange[1],
    "editorMarkerNavigationInfo.background": colors.blue[1],
    "editorMarkerNavigationWarning.background": colors.orange[1],
    "editorOverviewRuler.background": "#00000000",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.modifiedForeground": colors.yellow[1],
    "editorRuler.foreground": colors.ink[1],
    "editor.stackFrameHighlightBackground": "#f9e2af26",
    "editor.focusedStackFrameHighlightBackground": "#a6e3a126",
    "editorStickyScrollHover.background": colors.glow[0],
    "editorSuggestWidget.background": colors.canvas[1],
    "editorSuggestWidget.border": colors.canvas[3],
    "editorSuggestWidget.foreground": colors.ink[3],
    "editorSuggestWidget.highlightForeground": colors.purple[1],
    "editorSuggestWidget.selectedBackground": colors.glow[0],
    "editorWhitespace.foreground": colors.ink[0],
    "editorWidget.background": colors.canvas[1],
    "editorWidget.foreground": colors.ink[3],
    "editorWidget.resizeBorder": colors.canvas[3],
    "editorLightBulb.foreground": colors.yellow[1],
    "editorError.foreground": colors.orange[1],
    "editorError.border": "#00000000",
    "editorError.background": "#00000000",
    "editorWarning.foreground": colors.orange[1],
    "editorWarning.border": "#00000000",
    "editorWarning.background": "#00000000",
    "editorInfo.foreground": colors.blue[1],
    "editorInfo.border": "#00000000",
    "editorInfo.background": "#00000000",
    "problemsErrorIcon.foreground": colors.orange[1],
    "problemsInfoIcon.foreground": colors.blue[1],
    "problemsWarningIcon.foreground": colors.orange[1],
    "extensionButton.prominentForeground": colors.canvas[2],
    "extensionButton.prominentBackground": colors.purple[1],
    "extensionButton.separator": colors.canvas[0],
    "extensionButton.prominentHoverBackground": colors.purple[2],
    "extensionBadge.remoteBackground": colors.blue[1],
    "extensionBadge.remoteForeground": colors.canvas[2],
    "extensionIcon.starForeground": colors.yellow[1],
    "extensionIcon.verifiedForeground": colors.green[1],
    "extensionIcon.preReleaseForeground": colors.ink[1],
    "extensionIcon.sponsorForeground": colors.pink[2],
    "gitDecoration.addedResourceForeground": colors.green[1],
    "gitDecoration.conflictingResourceForeground": colors.purple[1],
    "gitDecoration.deletedResourceForeground": colors.orange[1],
    "gitDecoration.ignoredResourceForeground": colors.ink[0],
    "gitDecoration.modifiedResourceForeground": colors.yellow[1],
    "gitDecoration.stageDeletedResourceForeground": colors.orange[1],
    "gitDecoration.stageModifiedResourceForeground": colors.yellow[1],
    "gitDecoration.submoduleResourceForeground": colors.blue[1],
    "gitDecoration.untrackedResourceForeground": colors.green[1],
    "scmGraph.historyItemRefColor": colors.blue[1],
    "scmGraph.historyItemBaseRefColor": colors.orange[1],
    "scmGraph.historyItemRemoteRefColor": colors.purple[1],
    "scmGraph.foreground1": colors.purple[1],
    "scmGraph.foreground2": colors.magenta[1],
    "scmGraph.foreground3": colors.pink[1],
    "scmGraph.foreground4": colors.orange[1],
    "scmGraph.foreground5": colors.yellow[1],
    "input.background": colors.glow[0],
    "input.border": colors.canvas[3],
    "input.foreground": colors.ink[3],
    "input.placeholderForeground": colors.ink[1],
    "inputOption.hoverBackground": colors.glow[2],
    "inputOption.activeBackground": colors.glow[3],
    "inputOption.activeBorder": colors.purple[1],
    "inputOption.activeForeground": colors.ink[3],
    "inputValidation.errorBackground": colors.orange[1],
    "inputValidation.errorBorder": colors.orange[2],
    "inputValidation.errorForeground": colors.canvas[2],
    "inputValidation.infoBackground": colors.blue[1],
    "inputValidation.infoBorder": colors.blue[2],
    "inputValidation.infoForeground": colors.canvas[2],
    "inputValidation.warningBackground": colors.orange[1],
    "inputValidation.warningBorder": colors.orange[2],
    "inputValidation.warningForeground": colors.canvas[2],
    "list.activeSelectionBackground": colors.glow[0],
    "list.activeSelectionForeground": colors.ink[3],
    "list.dropBackground": colors.glow[0],
    "list.focusBackground": colors.glow[0],
    "list.focusForeground": colors.ink[3],
    "list.focusOutline": "#00000000",
    "list.highlightForeground": colors.purple[1],
    "list.hoverBackground": colors.glow[1],
    "list.hoverForeground": colors.ink[3],
    "list.inactiveSelectionBackground": colors.glow[0],
    "list.inactiveSelectionForeground": colors.ink[3],
    "list.warningForeground": colors.orange[1],
    "listFilterWidget.background": colors.glow[0],
    "listFilterWidget.noMatchesOutline": colors.orange[1],
    "listFilterWidget.outline": "#00000000",
    "tree.indentGuidesStroke": colors.glow[4],
    "tree.inactiveIndentGuidesStroke": colors.glow[2],
    "menu.background": colors.canvas[0],
    "menu.border": colors.canvas[4],
    "menu.foreground": colors.ink[3],
    "menu.selectionBackground": colors.glow[3],
    "menu.selectionBorder": "#00000000",
    "menu.selectionForeground": colors.ink[3],
    "menu.separatorBackground": colors.canvas[3],
    "menubar.selectionBackground": colors.glow[0],
    "menubar.selectionForeground": colors.ink[3],
    "merge.commonContentBackground": colors.glow[0],
    "merge.commonHeaderBackground": colors.glow[1],
    "merge.currentContentBackground": "#a6e3a133",
    "merge.currentHeaderBackground": "#a6e3a166",
    "merge.incomingContentBackground": "#89b4fa33",
    "merge.incomingHeaderBackground": "#89b4fa66",
    "minimap.background": "#00000000",
    "minimap.findMatchHighlight": "#89dceb4d",
    "minimap.selectionHighlight": "#585b70bf",
    "minimap.selectionOccurrenceHighlight": "#585b70bf",
    "minimap.warningHighlight": "#fab387bf",
    "minimap.errorHighlight": "#f38ba8bf",
    "minimapSlider.background": colors.glow[1],
    "minimapSlider.hoverBackground": colors.glow[2],
    "minimapSlider.activeBackground": colors.glow[3],
    "minimapGutter.addedBackground": "#a6e3a1bf",
    "minimapGutter.deletedBackground": "#f38ba8bf",
    "minimapGutter.modifiedBackground": "#f9e2afbf",
    "notificationCenter.border": colors.purple[1],
    "notificationCenterHeader.foreground": colors.ink[3],
    "notificationCenterHeader.background": colors.canvas[1],
    "notificationToast.border": colors.purple[1],
    "notifications.foreground": colors.ink[3],
    "notifications.background": colors.canvas[1],
    "notifications.border": colors.purple[1],
    "notificationLink.foreground": colors.blue[1],
    "notificationsErrorIcon.foreground": colors.orange[1],
    "notificationsWarningIcon.foreground": colors.orange[1],
    "notificationsInfoIcon.foreground": colors.blue[1],
    "panel.background": colors.canvas[0],
    "panel.border": colors.canvas[3],
    "panelSection.border": colors.canvas[3],
    "panelSection.dropBackground": colors.glow[0],
    "panelTitle.activeBorder": colors.purple[1],
    "panelTitle.activeForeground": colors.ink[3],
    "panelTitle.inactiveForeground": colors.ink[0],
    "peekView.border": colors.purple[1],
    "peekViewEditor.background": colors.canvas[1],
    "peekViewEditorGutter.background": colors.canvas[1],
    "peekViewEditor.matchHighlightBackground": "#89dceb4d",
    "peekViewEditor.matchHighlightBorder": "#00000000",
    "peekViewResult.background": colors.canvas[1],
    "peekViewResult.fileForeground": colors.ink[3],
    "peekViewResult.lineForeground": colors.ink[3],
    "peekViewResult.matchHighlightBackground": "#89dceb4d",
    "peekViewResult.selectionBackground": colors.glow[0],
    "peekViewResult.selectionForeground": colors.ink[3],
    "peekViewTitle.background": colors.canvas[0],
    "peekViewTitleDescription.foreground": "#bac2deb3",
    "peekViewTitleLabel.foreground": colors.ink[3],
    "pickerGroup.border": colors.purple[1],
    "pickerGroup.foreground": colors.purple[1],
    "progressBar.background": colors.purple[1],
    "scrollbar.background": "#00000000",
    "scrollbar.shadow": "#00000030",
    "scrollbarSlider.activeBackground": colors.glow[3],
    "scrollbarSlider.background": colors.glow[1],
    "scrollbarSlider.hoverBackground": colors.glow[2],
    "settings.focusedRowBackground": colors.glow[1],
    "settings.headerForeground": colors.ink[3],
    "settings.modifiedItemIndicator": colors.purple[1],
    "settings.dropdownBackground": colors.glow[0],
    "settings.dropdownListBorder": "#00000000",
    "settings.textInputBackground": colors.glow[0],
    "settings.textInputBorder": "#00000000",
    "settings.numberInputBackground": colors.glow[0],
    "settings.numberInputBorder": "#00000000",
    "sideBar.background": colors.canvas[1],
    "sideBar.dropBackground": colors.glow[0],
    "sideBar.foreground": colors.ink[3],
    "sideBar.border": colors.canvas[3],
    "sideBarSectionHeader.background": colors.canvas[1],
    "sideBarSectionHeader.foreground": colors.ink[3],
    "sideBarTitle.foreground": colors.purple[1],
    "banner.background": colors.glow[0],
    "banner.foreground": colors.ink[3],
    "banner.iconForeground": colors.ink[3],
    "statusBar.background": colors.canvas[2],
    "statusBar.foreground": colors.ink[3],
    "statusBar.border": colors.canvas[3],
    "statusBar.noFolderBackground": colors.canvas[2],
    "statusBar.noFolderForeground": colors.ink[3],
    "statusBar.noFolderBorder": "#00000000",
    "statusBar.debuggingBackground": colors.orange[1],
    "statusBar.debuggingForeground": colors.canvas[2],
    "statusBar.debuggingBorder": "#00000000",
    "statusBarItem.remoteBackground": colors.blue[1],
    "statusBarItem.remoteForeground": colors.canvas[2],
    "statusBarItem.activeBackground": colors.glow[1],
    "statusBarItem.hoverBackground": colors.glow[1],
    "statusBarItem.prominentForeground": colors.purple[1],
    "statusBarItem.prominentBackground": "#00000000",
    "statusBarItem.prominentHoverBackground": colors.glow[1],
    "statusBarItem.errorForeground": colors.orange[1],
    "statusBarItem.errorBackground": "#00000000",
    "statusBarItem.warningForeground": colors.orange[1],
    "statusBarItem.warningBackground": "#00000000",
    "commandCenter.foreground": colors.ink[2],
    "commandCenter.inactiveForeground": colors.ink[2],
    "commandCenter.activeForeground": colors.purple[1],
    "commandCenter.background": colors.canvas[1],
    "commandCenter.activeBackground": colors.glow[1],
    "commandCenter.border": "#00000000",
    "commandCenter.inactiveBorder": "#00000000",
    "commandCenter.activeBorder": colors.purple[1],
    "tab.activeBackground": colors.canvas[0],
    "tab.activeBorder": "#00000000",
    "tab.activeBorderTop": colors.purple[1],
    "tab.activeForeground": colors.purple[1],
    "tab.activeModifiedBorder": colors.yellow[1],
    "tab.border": "#00000000",
    "tab.hoverBackground": colors.canvas[2],
    "tab.hoverBorder": "#00000000",
    "tab.hoverForeground": colors.purple[1],
    "tab.inactiveBackground": colors.canvas[1],
    "tab.inactiveForeground": colors.ink[2],
    "tab.inactiveModifiedBorder": colors.yellow[2] + "40",
    "tab.lastPinnedBorder": colors.purple[1],
    "tab.unfocusedActiveBackground": colors.canvas[1],
    "tab.unfocusedActiveBorder": "#00000000",
    "tab.unfocusedActiveBorderTop": colors.purple[1] + "40",
    "tab.unfocusedInactiveBackground": colors.canvas[0],
    "terminal.foreground": colors.ink[3],
    "terminal.ansiBlack": colors.canvas[1],
    "terminal.ansiRed": colors.orange[1],
    "terminal.ansiGreen": colors.green[1],
    "terminal.ansiYellow": colors.yellow[1],
    "terminal.ansiBlue": colors.blue[1],
    "terminal.ansiMagenta": colors.magenta[1],
    "terminal.ansiCyan": colors.cyan[1],
    "terminal.ansiWhite": colors.ink[0],
    "terminal.ansiBrightBlack": colors.canvas[2],
    "terminal.ansiBrightRed": colors.orange[2],
    "terminal.ansiBrightGreen": colors.green[2],
    "terminal.ansiBrightYellow": colors.yellow[2],
    "terminal.ansiBrightBlue": colors.blue[2],
    "terminal.ansiBrightMagenta": colors.magenta[2],
    "terminal.ansiBrightCyan": colors.cyan[2],
    "terminal.ansiBrightWhite": colors.ink[3],
    "terminal.selectionBackground": colors.glow[3],
    "terminal.inactiveSelectionBackground": colors.glow[1],
    "terminalCursor.background": colors.canvas[0],
    "terminalCursor.foreground": colors.yellow[2],
    "terminal.border": colors.canvas[3],
    "terminal.dropBackground": colors.glow[0],
    "terminal.tab.activeBorder": colors.purple[1],
    "terminalCommandDecoration.defaultBackground": colors.glow[3],
    "terminalCommandDecoration.successBackground": colors.green[1],
    "terminalCommandDecoration.errorBackground": colors.orange[1],
    "titleBar.activeBackground": colors.canvas[2],
    "titleBar.activeForeground": colors.ink[2],
    "titleBar.inactiveBackground": colors.canvas[2],
    "titleBar.inactiveForeground": colors.ink[1],
    "titleBar.border": colors.canvas[4],
    "welcomePage.tileBackground": colors.canvas[1],
    "welcomePage.progress.background": colors.canvas[2],
    "welcomePage.progress.foreground": colors.purple[1],
    "walkThrough.embeddedEditorBackground": colors.canvas[0],
    "symbolIcon.textForeground": colors.ink[3],
    "symbolIcon.arrayForeground": colors.orange[1],
    "symbolIcon.booleanForeground": colors.purple[1],
    "symbolIcon.classForeground": colors.yellow[1],
    "symbolIcon.colorForeground": colors.pink[2],
    "symbolIcon.constantForeground": colors.orange[1],
    "symbolIcon.constructorForeground": colors.purple[2],
    "symbolIcon.enumeratorForeground": colors.yellow[1],
    "symbolIcon.enumeratorMemberForeground": colors.yellow[1],
    "symbolIcon.eventForeground": colors.cyan[1],
    "symbolIcon.fieldForeground": colors.ink[3],
    "symbolIcon.fileForeground": colors.purple[1],
    "symbolIcon.folderForeground": colors.purple[1],
    "symbolIcon.functionForeground": colors.blue[1],
    "symbolIcon.interfaceForeground": colors.yellow[1],
    "symbolIcon.keyForeground": colors.cyan[1],
    "symbolIcon.keywordForeground": colors.purple[1],
    "symbolIcon.methodForeground": colors.blue[1],
    "symbolIcon.moduleForeground": colors.ink[3],
    "symbolIcon.namespaceForeground": colors.yellow[1],
    "symbolIcon.nullForeground": colors.pink[1],
    "symbolIcon.numberForeground": colors.orange[1],
    "symbolIcon.objectForeground": colors.yellow[1],
    "symbolIcon.operatorForeground": colors.cyan[1],
    "symbolIcon.packageForeground": colors.orange[2],
    "symbolIcon.propertyForeground": colors.pink[1],
    "symbolIcon.referenceForeground": colors.yellow[1],
    "symbolIcon.snippetForeground": colors.green[1],
    "symbolIcon.stringForeground": colors.green[1],
    "symbolIcon.structForeground": colors.cyan[1],
    "symbolIcon.typeParameterForeground": colors.pink[1],
    "symbolIcon.unitForeground": colors.ink[3],
    "symbolIcon.variableForeground": colors.ink[2],
    "charts.foreground": colors.ink[3],
    "charts.lines": colors.ink[2],
    "charts.red": colors.orange[1],
    "charts.blue": colors.blue[1],
    "charts.yellow": colors.yellow[1],
    "charts.orange": colors.orange[1],
    "charts.green": colors.green[1],
    "charts.purple": colors.purple[1],
    "errorLens.errorBackground": "#f38ba826",
    "errorLens.errorBackgroundLight": "#f38ba826",
    "errorLens.errorForeground": colors.orange[1],
    "errorLens.errorForegroundLight": colors.orange[2],
    "errorLens.errorMessageBackground": "#f38ba826",
    "errorLens.hintBackground": "#a6e3a126",
    "errorLens.hintBackgroundLight": "#a6e3a126",
    "errorLens.hintForeground": colors.green[1],
    "errorLens.hintForegroundLight": colors.green[2],
    "errorLens.hintMessageBackground": "#a6e3a126",
    "errorLens.infoBackground": "#89b4fa26",
    "errorLens.infoBackgroundLight": "#89b4fa26",
    "errorLens.infoForeground": colors.blue[1],
    "errorLens.infoForegroundLight": colors.blue[2],
    "errorLens.infoMessageBackground": "#89b4fa26",
    "errorLens.statusBarErrorForeground": colors.orange[1],
    "errorLens.statusBarHintForeground": colors.green[1],
    "errorLens.statusBarIconErrorForeground": colors.orange[1],
    "errorLens.statusBarIconWarningForeground": colors.orange[1],
    "errorLens.statusBarInfoForeground": colors.blue[1],
    "errorLens.statusBarWarningForeground": colors.orange[1],
    "errorLens.warningBackground": "#fab38726",
    "errorLens.warningBackgroundLight": "#fab38726",
    "errorLens.warningForeground": colors.orange[1],
    "errorLens.warningForegroundLight": colors.orange[1],
    "errorLens.warningMessageBackground": "#fab38726",
    "issues.closed": colors.purple[1],
    "issues.newIssueDecoration": colors.yellow[2],
    "issues.open": colors.green[1],
    "pullRequests.closed": colors.orange[1],
    "pullRequests.draft": colors.ink[2],
    "pullRequests.merged": colors.purple[1],
    "pullRequests.notification": colors.ink[3],
    "pullRequests.open": colors.green[1],
    "editorBracketHighlight.foreground1": colors.pink[1],
    "editorBracketHighlight.foreground2": colors.orange[1],
    "editorBracketHighlight.foreground3": colors.yellow[1],
    "editorBracketHighlight.foreground4": colors.green[1],
    "editorBracketHighlight.foreground5": colors.cyan[1],
    "editorBracketHighlight.foreground6": colors.blue[1],
    "editorBracketHighlight.unexpectedBracket.foreground": colors.pink[2],
    "button.secondaryBorder": colors.purple[1],
    "table.headerBackground": colors.glow[0],
    "table.headerForeground": colors.ink[3],
    "list.focusAndSelectionBackground": colors.glow[0],
  },
  semanticTokenColors: {
    "enumMember": {
      foreground: colors.cyan[1],
    },
    "selfKeyword": {
      foreground: colors.orange[1],
    },
    "boolean": {
      foreground: colors.orange[1],
    },
    "number": {
      foreground: colors.orange[1],
    },
    "variable.defaultLibrary": {
      foreground: colors.pink[1],
    },
    "class:python": {
      foreground: colors.yellow[1],
    },
    "class.builtin:python": {
      foreground: colors.purple[1],
    },
    "variable.typeHint:python": {
      foreground: colors.yellow[1],
    },
    "function.decorator:python": {
      foreground: colors.orange[1],
    },
    "variable.readonly:javascript": {
      foreground: colors.ink[3],
    },
    "variable.readonly:typescript": {
      foreground: colors.ink[3],
    },
    "property.readonly:javascript": {
      foreground: colors.ink[3],
    },
    "property.readonly:typescript": {
      foreground: colors.ink[3],
    },
    "variable.readonly:javascriptreact": {
      foreground: colors.ink[3],
    },
    "variable.readonly:typescriptreact": {
      foreground: colors.ink[3],
    },
    "property.readonly:javascriptreact": {
      foreground: colors.ink[3],
    },
    "property.readonly:typescriptreact": {
      foreground: colors.ink[3],
    },
    "variable.readonly:scala": {
      foreground: colors.ink[3],
    },
    "type.defaultLibrary:go": {
      foreground: colors.purple[1],
    },
    "variable.readonly.defaultLibrary:go": {
      foreground: colors.purple[1],
    },
    "tomlArrayKey": {
      foreground: colors.blue[1],
      fontStyle: "",
    },
    "tomlTableKey": {
      foreground: colors.blue[1],
      fontStyle: "",
    },
    "builtinAttribute.attribute.library:rust": {
      foreground: colors.blue[1],
    },
    "generic.attribute:rust": {
      foreground: colors.ink[3],
    },
    "constant.builtin.readonly:nix": {
      foreground: colors.purple[1],
    },
    "heading": {
      foreground: colors.orange[1],
    },
    "text.emph": {
      foreground: colors.orange[1],
      fontStyle: "italic",
    },
    "text.strong": {
      foreground: colors.orange[1],
      fontStyle: "bold",
    },
    "text.math": {
      foreground: "#f2cdcd",
    },
    "pol": {
      foreground: "#f2cdcd",
    },
  },
  tokenColors: [
    {
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: {
        foreground: "#6C6C93",
      },
    },
    {
      scope: [
        "delimiter.bracket",
        "delimiter",
        "invalid.illegal.character-not-allowed-here.html",
        "keyword.operator.rest",
        "keyword.operator.spread",
        "keyword.operator.type.annotation",
        "keyword.operator.relational",
        "keyword.operator.assignment",
        "keyword.operator.type",
        "meta.brace",
        "meta.tag.block.any.html",
        "meta.tag.inline.any.html",
        "meta.tag.structure.input.void.html",
        "meta.type.annotation",
        "meta.embedded.block.github-actions-expression",
        "storage.type.function.arrow",
        "meta.objectliteral.ts",
        "punctuation",
        "punctuation.definition.string.begin.html.vue",
        "punctuation.definition.string.end.html.vue",
      ],
      settings: {
        foreground: "#666666",
      },
    },
    {
      scope: ["constant", "entity.name.constant", "variable.language", "meta.definition.variable"],
      settings: {
        foreground: "#DB8380",
      },
    },
    {
      scope: ["entity", "entity.name"],
      settings: {
        foreground: "#85B0ED",
      },
    },
    {
      scope: "variable.parameter.function",
      settings: {
        foreground: "#E0E0EB",
      },
    },
    {
      scope: ["entity.name.tag", "tag.html"],
      settings: {
        foreground: "#D08DD9",
      },
    },
    {
      scope: "entity.name.function",
      settings: {
        foreground: "#85B0ED",
      },
    },
    {
      scope: ["keyword", "storage.type.class.jsdoc", "punctuation.definition.template-expression"],
      settings: {
        foreground: "#D08DD9",
      },
    },
    {
      scope: [
        "storage",
        "storage.type",
        "support.type.builtin",
        "constant.language.undefined",
        "constant.language.null",
        "constant.language.import-export-all.ts",
      ],
      settings: {
        foreground: "#D08DD9",
      },
    },
    {
      scope: [
        "text.html.derivative",
        "storage.modifier.package",
        "storage.modifier.import",
        "storage.type.java",
      ],
      settings: {
        foreground: "#E0E0EB",
      },
    },
    {
      scope: ["string", "string punctuation.section.embedded source", "attribute.value"],
      settings: {
        foreground: "#55BD97",
      },
    },
    {
      scope: ["punctuation.definition.string"],
      settings: {
        foreground: "#55BD9777",
      },
    },
    {
      scope: ["punctuation.support.type.property-name"],
      settings: {
        foreground: "#948BD977",
      },
    },
    {
      scope: "support",
      settings: {
        foreground: "#948BD9",
      },
    },
    {
      scope: [
        "property",
        "meta.property-name",
        "meta.object-literal.key",
        "entity.name.tag.yaml",
        "attribute.name",
      ],
      settings: {
        foreground: "#948BD9",
      },
    },
    {
      scope: ["entity.other.attribute-name", "invalid.deprecated.entity.other.attribute-name.html"],
      settings: {
        foreground: "#D06A97",
      },
    },
    {
      scope: ["variable", "identifier"],
      settings: {
        foreground: "#D06A97",
      },
    },
    {
      scope: ["support.type.primitive", "entity.name.type"],
      settings: {
        foreground: "#CE9F7D",
      },
    },
    {
      scope: "namespace",
      settings: {
        foreground: "#55BD97",
      },
    },
    {
      scope: ["keyword.operator", "keyword.operator.assignment.compound", "meta.var.expr.ts"],
      settings: {
        foreground: "#78D0D0",
      },
    },
    {
      scope: "invalid.broken",
      settings: {
        fontStyle: "italic",
        foreground: "#fdaeb7",
      },
    },
    {
      scope: "invalid.deprecated",
      settings: {
        fontStyle: "italic",
        foreground: "#fdaeb7",
      },
    },
    {
      scope: "invalid.illegal",
      settings: {
        fontStyle: "italic",
        foreground: "#fdaeb7",
      },
    },
    {
      scope: "invalid.unimplemented",
      settings: {
        fontStyle: "italic",
        foreground: "#fdaeb7",
      },
    },
    {
      scope: "carriage-return",
      settings: {
        fontStyle: "italic underline",
        background: "#f97583",
        foreground: "#24292e",
        content: "^M",
      },
    },
    {
      scope: "message.error",
      settings: {
        foreground: "#fdaeb7",
      },
    },
    {
      scope: "string variable",
      settings: {
        foreground: "#55BD97",
      },
    },
    {
      scope: ["source.regexp", "string.regexp"],
      settings: {
        foreground: "#CE9F7D",
      },
    },
    {
      scope: [
        "string.regexp.character-class",
        "string.regexp constant.character.escape",
        "string.regexp source.ruby.embedded",
        "string.regexp string.regexp.arbitrary-repitition",
      ],
      settings: {
        foreground: "#55BD97",
      },
    },
    {
      scope: "string.regexp constant.character.escape",
      settings: {
        foreground: "#CE9F7D",
      },
    },
    {
      scope: ["support.constant"],
      settings: {
        foreground: "#DB8380",
      },
    },
    {
      scope: ["keyword.operator.quantifier.regexp", "constant.numeric", "number"],
      settings: {
        foreground: "#DB8380",
      },
    },
    {
      scope: ["keyword.other.unit"],
      settings: {
        foreground: "#D08DD9",
      },
    },
    {
      scope: ["constant.language.boolean", "constant.language"],
      settings: {
        foreground: "#D08DD9",
      },
    },
    {
      scope: "meta.module-reference",
      settings: {
        foreground: "#4d9375",
      },
    },
    {
      scope: "punctuation.definition.list.begin.markdown",
      settings: {
        foreground: "#DB8380",
      },
    },
    {
      scope: ["markup.heading", "markup.heading entity.name"],
      settings: {
        fontStyle: "bold",
        foreground: "#4d9375",
      },
    },
    {
      scope: "markup.quote",
      settings: {
        foreground: "#D06A97",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
        foreground: "#E0E0EB",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        fontStyle: "bold",
        foreground: "#E0E0EB",
      },
    },
    {
      scope: "markup.raw",
      settings: {
        foreground: "#4d9375",
      },
    },
    {
      scope: ["markup.deleted", "meta.diff.header.from-file", "punctuation.definition.deleted"],
      settings: {
        background: "#86181d",
        foreground: "#fdaeb7",
      },
    },
    {
      scope: ["markup.inserted", "meta.diff.header.to-file", "punctuation.definition.inserted"],
      settings: {
        background: "#144620",
        foreground: "#85e89d",
      },
    },
    {
      scope: ["markup.changed", "punctuation.definition.changed"],
      settings: {
        background: "#c24e00",
        foreground: "#ffab70",
      },
    },
    {
      scope: ["markup.ignored", "markup.untracked"],
      settings: {
        foreground: "#2f363d",
        background: "#79b8ff",
      },
    },
    {
      scope: "meta.diff.range",
      settings: {
        foreground: "#b392f0",
        fontStyle: "bold",
      },
    },
    {
      scope: "meta.diff.header",
      settings: {
        foreground: "#79b8ff",
      },
    },
    {
      scope: "meta.separator",
      settings: {
        fontStyle: "bold",
        foreground: "#79b8ff",
      },
    },
    {
      scope: "meta.output",
      settings: {
        foreground: "#79b8ff",
      },
    },
    {
      scope: [
        "brackethighlighter.tag",
        "brackethighlighter.curly",
        "brackethighlighter.round",
        "brackethighlighter.square",
        "brackethighlighter.angle",
        "brackethighlighter.quote",
      ],
      settings: {
        foreground: "#d1d5da",
      },
    },
    {
      scope: "brackethighlighter.unmatched",
      settings: {
        foreground: "#fdaeb7",
      },
    },
    {
      scope: [
        "constant.other.reference.link",
        "string.other.link",
        "punctuation.definition.string.begin.markdown",
        "punctuation.definition.string.end.markdown",
      ],
      settings: {
        foreground: "#55BD97",
      },
    },
    {
      scope: ["markup.underline.link.markdown", "markup.underline.link.image.markdown"],
      settings: {
        foreground: "#6C6C93",
        fontStyle: "underline",
      },
    },
    {
      scope: ["type.identifier", "constant.other.character-class.regexp"],
      settings: {
        foreground: "#CE9F7D",
      },
    },
    {
      scope: ["entity.other.attribute-name.html.vue"],
      settings: {
        foreground: "#85B0ED",
      },
    },
    {
      scope: ["invalid.illegal.unrecognized-tag.html"],
      settings: {
        fontStyle: "normal",
      },
    },
  ],
};
