const colors = {
  canvas: ["#1A1A23", "#1E1E29", "#22222F", "#2B2B3B", "#353447"],
  ink: ["#E0E0EB", "#9C9CB5", "#6C6C93", "#5E5E6E"],
  glow: ["#CECCFF0D", "#CECCFF16", "#B9B3FF22", "#A099FF2D", "#B9B3FF36"],
  pink: ["#E08BB1", "#D06A97", "#944669"],
  orange: ["#E09C9B", "#DB8380", "#B36766"],
  yellow: ["#D4B49D", "#CE9F7D", "#9C785F"],
  green: ["#78CCAD", "#55BD97", "#3A8A6D"],
  cyan: ["#A6DEDE", "#78D0D0", "#498F8F"],
  blue: ["#A3C6F7", "#85B0ED", "#688ABA"],
  purple: ["#B3ACE8", "#948BD9", "#6D65A6"],
  magenta: ["#DEAEE6", "#D08DD9", "#9C5BA6"],
};

const darkTheme = {
  name: "Technicolor Dark",
  appearance: "dark",
  style: {
    "border": colors.canvas[4],
    "border.variant": colors.canvas[3],
    "border.focused": colors.purple[2],
    "border.selected": colors.purple[2],
    "border.transparent": "#00000000",
    "border.disabled": colors.canvas[1],

    "elevated_surface.background": colors.canvas[1],
    "surface.background": colors.canvas[1],
    "background": colors.canvas[2],

    "element.background": colors.glow[0],
    "element.hover": colors.glow[1],
    "element.active": colors.glow[2],
    "element.selected": colors.glow[3],
    "element.selection_background": colors.glow[3],
    "element.disabled": "#00000000",

    "drop_target.background": colors.cyan[2] + "22",
    "drop_target.border": colors.canvas[3],

    "ghost_element.background": "#00000000",
    "ghost_element.hover": colors.glow[1],
    "ghost_element.active": colors.glow[2],
    "ghost_element.selected": colors.glow[3],
    "ghost_element.disabled": "#00000000",

    "text": colors.ink[0],
    "text.muted": colors.ink[1],
    "text.placeholder": colors.ink[2],
    "text.disabled": colors.ink[3],
    "text.accent": colors.purple[1],

    "icon": colors.ink[0],
    "icon.muted": colors.ink[1],
    "icon.disabled": colors.ink[3],
    "icon.placeholder": colors.ink[2],
    "icon.accent": colors.purple[1],

    "status_bar.background": colors.canvas[2],
    "title_bar.background": colors.canvas[2],
    "title_bar.inactive_background": colors.canvas[1],
    "toolbar.background": colors.canvas[0],
    "tab_bar.background": colors.canvas[1],
    "tab.inactive_background": colors.canvas[1],
    "tab.active_background": colors.canvas[0],
    "search.match_background": colors.green[2] + "22",
    "search.active_match_background": colors.green[0] + "22",

    "panel.background": colors.canvas[1],
    "panel.overlay_background": colors.canvas[1],
    "panel.overlay_hover": colors.canvas[2],
    "panel.focused_border": colors.purple[2],
    "panel.indent_guide": colors.glow[1],
    "panel.indent_guide_hover": colors.glow[2],
    "panel.indent_guide_active": colors.glow[4],
    "pane.focused_border": colors.purple[2],

    "scrollbar.thumb.background": colors.glow[0],
    "scrollbar.thumb.hover_background": colors.glow[1],
    "scrollbar.thumb.active_background": colors.glow[2],
    "scrollbar.thumb.border": colors.canvas[4],
    "scrollbar.track.background": "#00000000",
    "scrollbar.track.border": colors.canvas[3],

    "minimap.thumb.background": colors.glow[0],
    "minimap.thumb.hover_background": colors.glow[1],
    "minimap.thumb.active_background": colors.glow[2],
    "minimap.thumb.border": colors.canvas[4],

    "editor.foreground": colors.ink[1],
    "editor.background": colors.canvas[0],
    "editor.gutter.background": colors.canvas[0],
    "editor.subheader.background": colors.canvas[1],
    "editor.active_line.background": colors.glow[0],
    "editor.highlighted_line.background": colors.glow[1],
    "editor.line_number": colors.ink[2],
    "editor.active_line_number": colors.ink[0],
    "editor.hover_line_number": colors.ink[1],
    "editor.debugger_active_line.background": colors.pink[0] + "AA",
    "editor.invisible": colors.ink[3],
    "editor.indent_guide": colors.glow[2],
    "editor.indent_guide_active": colors.glow[4],
    "editor.wrap_guide": colors.glow[2],
    "editor.active_wrap_guide": colors.glow[4],
    "editor.document_highlight.bracket_background": colors.glow[3],
    "editor.document_highlight.read_background": colors.magenta[2] + "22",
    "editor.document_highlight.write_background": colors.blue[2] + "22",

    "terminal.background": colors.canvas[0],
    "terminal.foreground": colors.ink[1],
    "terminal.bright_foreground": colors.ink[0],
    "terminal.dim_foreground": colors.ink[2],
    "terminal.ansi.black": colors.canvas[1],
    "terminal.ansi.bright_black": colors.canvas[2],
    "terminal.ansi.dim_black": colors.canvas[0],
    "terminal.ansi.red": colors.orange[1],
    "terminal.ansi.bright_red": colors.orange[0],
    "terminal.ansi.dim_red": colors.orange[2],
    "terminal.ansi.green": colors.green[1],
    "terminal.ansi.bright_green": colors.green[0],
    "terminal.ansi.dim_green": colors.green[2],
    "terminal.ansi.yellow": colors.yellow[1],
    "terminal.ansi.bright_yellow": colors.yellow[0],
    "terminal.ansi.dim_yellow": colors.yellow[2],
    "terminal.ansi.blue": colors.blue[1],
    "terminal.ansi.bright_blue": colors.blue[0],
    "terminal.ansi.dim_blue": colors.blue[2],
    "terminal.ansi.magenta": colors.magenta[1],
    "terminal.ansi.bright_magenta": colors.magenta[0],
    "terminal.ansi.dim_magenta": colors.magenta[2],
    "terminal.ansi.cyan": colors.cyan[1],
    "terminal.ansi.bright_cyan": colors.cyan[0],
    "terminal.ansi.dim_cyan": colors.cyan[2],
    "terminal.ansi.white": colors.ink[1],
    "terminal.ansi.bright_white": colors.ink[0],
    "terminal.ansi.dim_white": colors.ink[2],
    "link_text.hover": colors.purple[1],

    "version_control.added": colors.green[1],
    "version_control.modified": colors.purple[1],
    "version_control.word_added": colors.green[2] + "22",
    "version_control.word_deleted": colors.pink[2] + "22",
    "version_control.renamed": colors.cyan[1],
    "version_control.conflict": colors.magenta[1],
    "version_control.ignored": colors.ink[3],
    "version_control.deleted": colors.pink[1],
    "version_control.conflict_marker.ours": colors.blue[1],
    "version_control.conflict_marker.theirs": colors.yellow[1],

    "conflict": colors.magenta[1],
    "conflict.background": colors.magenta[2] + "22",
    "conflict.border": colors.magenta[2],
    "created": colors.green[1],
    "created.background": colors.green[2] + "22",
    "created.border": colors.green[2],
    "deleted": colors.pink[1],
    "deleted.background": colors.pink[2] + "22",
    "deleted.border": colors.pink[2],
    "error": colors.orange[1],
    "error.background": colors.orange[2] + "22",
    "error.border": colors.orange[2],
    "hidden": colors.ink[3],
    "hidden.background": "#00000000",
    "hidden.border": colors.canvas[1],
    "hint": colors.ink[2],
    "hint.background": colors.glow[0],
    "hint.border": colors.canvas[3],
    "ignored": colors.ink[3],
    "ignored.background": "#00000000",
    "ignored.border": colors.canvas[1],
    "info": colors.blue[1],
    "info.background": colors.blue[2] + "22",
    "info.border": colors.blue[2],
    "modified": colors.purple[1],
    "modified.background": colors.purple[2] + "22",
    "modified.border": colors.purple[2],
    "predictive": colors.purple[2],
    "predictive.background": colors.glow[0],
    "predictive.border": colors.purple[2],
    "renamed": colors.cyan[1],
    "renamed.background": colors.cyan[2] + "22",
    "renamed.border": colors.cyan[2],
    "success": colors.green[1],
    "success.background": colors.green[2] + "22",
    "success.border": colors.green[2],
    "unreachable": colors.pink[2],
    "unreachable.background": colors.glow[0],
    "unreachable.border": colors.pink[2],
    "warning": colors.yellow[1],
    "warning.background": colors.yellow[2] + "22",
    "warning.border": colors.yellow[2],

    "players": [
      {
        cursor: colors.purple[1],
        background: colors.purple[1],
        selection: colors.purple[2] + "22",
      },
      { cursor: colors.pink[1], background: colors.pink[1], selection: colors.pink[2] + "22" },
      {
        cursor: colors.yellow[1],
        background: colors.yellow[1],
        selection: colors.yellow[2] + "22",
      },
      {
        cursor: colors.magenta[1],
        background: colors.magenta[1],
        selection: colors.magenta[2] + "22",
      },
      { cursor: colors.cyan[1], background: colors.cyan[1], selection: colors.cyan[2] + "22" },
      {
        cursor: colors.orange[1],
        background: colors.orange[1],
        selection: colors.orange[2] + "22",
      },
      { cursor: colors.green[1], background: colors.green[1], selection: colors.green[2] + "22" },
      { cursor: colors.blue[1], background: colors.blue[1], selection: colors.blue[2] + "22" },
    ],

    "syntax": {
      "attribute": { color: colors.purple[1] },
      "boolean": { color: colors.magenta[1] },
      "comment": { color: colors.ink[2], font_style: "italic" },
      "comment.doc": { color: colors.ink[2], font_style: "italic" },
      "constant": { color: colors.orange[1] },
      "constructor": { color: colors.yellow[1] },
      "embedded": { color: colors.magenta[0] },
      "emphasis": { color: colors.purple[1], font_style: "italic" },
      "emphasis.strong": { color: colors.pink[1], font_weight: 700 },
      "enum": { color: colors.orange[1] },
      "function": { color: colors.blue[1] },
      "hint": { color: colors.blue[2] },
      "keyword": { color: colors.magenta[1] },
      "label": { color: colors.green[1] },
      "link_text": { color: colors.blue[1], font_style: "normal" },
      "link_uri": { color: colors.blue[2] },
      "namespace": { color: colors.green[1] },
      "number": { color: colors.orange[1] },
      "operator": { color: colors.cyan[1] },
      "predictive": { color: colors.cyan[2], font_style: "italic" },
      "preproc": { color: colors.magenta[1], font_weight: 700 },
      "primary": { color: colors.ink[0] },
      "property": { color: colors.purple[1] },
      "punctuation": { color: colors.blue[2] },
      "punctuation.bracket": { color: colors.purple[0] },
      "punctuation.delimiter": { color: colors.purple[2] },
      "punctuation.list_marker": { color: colors.cyan[1] },
      "punctuation.markup": { color: colors.magenta[1] },
      "punctuation.special": { color: colors.magenta[2] },
      "selector": { color: colors.yellow[1] },
      "selector.pseudo": { color: colors.cyan[1] },
      "string": { color: colors.green[1] },
      "string.escape": { color: colors.yellow[1], font_weight: 700 },
      "string.regex": { color: colors.cyan[1] },
      "string.special": { color: colors.pink[1] },
      "string.special.symbol": { color: colors.yellow[1], font_weight: 700 },
      "tag": { color: colors.blue[1] },
      "text.literal": { color: colors.green[1] },
      "title": { color: colors.yellow[1], font_weight: 400 },
      "type": { color: colors.yellow[1] },
      "variable": { color: colors.pink[1] },
      "variable.special": { color: colors.cyan[1] },
      "variant": { color: colors.purple[1] },
    },
  },
};

export const zedTheme = {
  $schema: "https://zed.dev/schema/themes/v0.2.0.json",
  name: "Technicolor",
  description: "Technicolor theme",
  author: "Phaux",
  themes: [darkTheme],
};
