import { colors } from "./colors.ts";
import packageJson from "./package.json" with { type: "json" };

export const vscodeThemeDark = {
  $schema: "vscode://schemas/color-theme",
  name: `${packageJson.name} Dark`,
  colors: {
    "focusBorder": colors.purple[1],
    "foreground": colors.ink[2],
    "disabledForeground": colors.ink[0],
    "descriptionForeground": colors.ink[1],
    "widget.border": colors.canvas[4],
    "widget.shadow": "#00000060",
    "selection.background": colors.purple[0],
    "errorForeground": colors.orange[1],
    "icon.foreground": colors.purple[1],
    "textBlockQuote.background": colors.canvas[1],
    "textBlockQuote.border": colors.purple[0],
    "textCodeBlock.background": colors.canvas[1],
    "textLink.activeForeground": colors.blue[2],
    "textLink.foreground": colors.blue[1],
    "textPreformat.background": colors.glow[0],
    "textPreformat.border": colors.canvas[3],
    "textPreformat.foreground": colors.ink[2],
    "textSeparator.foreground": colors.purple[1],
    "activityBar.background": colors.canvas[2],
    "activityBar.foreground": colors.purple[1],
    "activityBar.inactiveForeground": colors.ink[1],
    "activityBar.border": "#00000000",
    "activityBarBadge.background": colors.purple[1],
    "activityBarBadge.foreground": colors.canvas[0],
    "activityBar.activeBorder": "#00000000",
    "activityBar.activeBackground": "#00000000",
    "activityBar.activeFocusBorder": "#00000000",
    "activityBarTop.foreground": colors.purple[1],
    "activityBarTop.activeBorder": "#00000000",
    "activityBarTop.inactiveForeground": colors.ink[1],
    "badge.background": colors.glow[4],
    "badge.foreground": colors.ink[3],
    "breadcrumb.activeSelectionForeground": colors.purple[1],
    "breadcrumb.background": colors.canvas[0],
    "breadcrumb.focusForeground": colors.ink[3],
    "breadcrumb.foreground": colors.ink[2],
    "breadcrumbPicker.background": colors.canvas[1],
    "button.background": colors.purple[1],
    "button.foreground": colors.canvas[0],
    "button.border": "#00000000",
    "button.separator": "#00000000",
    "button.hoverBackground": colors.purple[2],
    "button.secondaryBackground": colors.glow[0],
    "button.secondaryBorder": colors.canvas[4],
    "button.secondaryForeground": colors.ink[3],
    "button.secondaryHoverBackground": colors.glow[1],
    "checkbox.background": colors.canvas[0],
    "checkbox.border": colors.canvas[4],
    "checkbox.foreground": colors.purple[1],
    "dropdown.background": colors.canvas[0],
    "dropdown.listBackground": colors.canvas[0],
    "dropdown.border": colors.canvas[3],
    "dropdown.foreground": colors.ink[3],
    "debugToolBar.background": colors.canvas[1],
    "debugToolBar.border": "#00000000",
    "debugExceptionWidget.background": colors.canvas[1],
    "debugExceptionWidget.border": colors.canvas[4],
    "diffEditor.border": colors.canvas[3],
    "diffEditor.insertedTextBackground": colors.green[0] + "60",
    "diffEditor.removedTextBackground": colors.pink[0] + "60",
    "diffEditor.insertedLineBackground": colors.green[0] + "20",
    "diffEditor.removedLineBackground": colors.pink[0] + "20",
    "diffEditor.diagonalFill": colors.glow[1],
    "diffEditorGutter.insertedLineBackground": colors.green[1],
    "diffEditorGutter.removedLineBackground": colors.pink[1],
    "diffEditorOverview.insertedForeground": colors.green[1],
    "diffEditorOverview.removedForeground": colors.pink[1],
    "editor.background": colors.canvas[0],
    "editor.findMatchBackground": colors.yellow[0] + "40",
    "editor.findMatchBorder": "#00000000",
    "editor.findMatchHighlightBackground": colors.yellow[0] + "60",
    "editor.findMatchHighlightBorder": "#00000000",
    "editor.findRangeHighlightBackground": colors.blue[0] + "40",
    "editor.findRangeHighlightBorder": "#00000000",
    "editor.foldBackground": colors.glow[0],
    "editor.foreground": colors.ink[2],
    "editor.hoverHighlightBackground": colors.glow[0],
    "editor.lineHighlightBackground": colors.glow[0],
    "editor.lineHighlightBorder": "#00000000",
    "editor.rangeHighlightBackground": colors.blue[0] + "40",
    "editor.rangeHighlightBorder": "#00000000",
    "editor.selectionBackground": colors.purple[0] + "60",
    "editor.selectionHighlightBackground": colors.purple[0] + "40",
    "editor.selectionHighlightBorder": "#00000000",
    "editor.wordHighlightBackground": colors.magenta[0] + "40",
    "editor.wordHighlightStrongBackground": colors.magenta[0] + "60",
    "editor.wordHighlightTextBackground": colors.magenta[0] + "40",
    "editorBracketMatch.background": colors.purple[2] + "60",
    "editorBracketMatch.border": "#00000000",
    "editorCodeLens.foreground": colors.ink[1],
    "editorCursor.background": colors.canvas[0],
    "editorCursor.foreground": colors.purple[2],
    "editorGroup.border": colors.canvas[3],
    "editorGroup.dropBackground": colors.purple[1] + "30",
    "editorGroup.emptyBackground": colors.canvas[0],
    "editorGroupHeader.tabsBackground": colors.canvas[2],
    "editorGutter.addedBackground": colors.green[1],
    "editorGutter.background": colors.canvas[0],
    "editorGutter.commentRangeForeground": colors.ink[0],
    "editorGutter.commentGlyphForeground": colors.purple[1],
    "editorGutter.deletedBackground": colors.pink[1],
    "editorGutter.foldingControlForeground": colors.ink[1],
    "editorGutter.modifiedBackground": colors.purple[1],
    "editorHoverWidget.background": colors.canvas[1],
    "editorHoverWidget.border": colors.canvas[4],
    "editorHoverWidget.foreground": colors.ink[2],
    "editorHoverWidget.highlightForeground": colors.purple[1],
    "editorIndentGuide.activeBackground1": colors.glow[4],
    "editorIndentGuide.background1": colors.glow[2],
    "editorInlayHint.foreground": colors.ink[1],
    "editorInlayHint.background": colors.glow[0],
    "editorInlayHint.typeForeground": colors.ink[1],
    "editorInlayHint.typeBackground": colors.glow[0],
    "editorInlayHint.parameterForeground": colors.ink[1],
    "editorInlayHint.parameterBackground": colors.glow[0],
    "editorLineNumber.activeForeground": colors.purple[1],
    "editorLineNumber.foreground": colors.ink[1],
    "editorLink.activeForeground": colors.blue[2],
    "editorMarkerNavigation.background": colors.canvas[1],
    "editorMarkerNavigationError.background": colors.orange[1],
    "editorMarkerNavigationInfo.background": colors.blue[1],
    "editorMarkerNavigationWarning.background": colors.yellow[1],
    "editorOverviewRuler.background": "#00000000",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.addedForeground": colors.green[1] + "A0",
    "editorOverviewRuler.modifiedForeground": colors.purple[1] + "A0",
    "editorOverviewRuler.deletedForeground": colors.pink[1] + "A0",
    "editorOverviewRuler.commonContentForeground": colors.glow[0],
    "editorOverviewRuler.currentContentForeground": colors.cyan[1] + "80",
    "editorOverviewRuler.incomingContentForeground": colors.blue[1] + "80",
    "editorOverviewRuler.inlineChatInserted": colors.cyan[1] + "80",
    "editorOverviewRuler.inlineChatRemoved": colors.orange[1] + "80",
    "editorOverviewRuler.infoForeground": colors.blue[1],
    "editorOverviewRuler.warningForeground": colors.yellow[1],
    "editorOverviewRuler.errorForeground": colors.orange[1],
    "editorOverviewRuler.bracketMatchForeground": colors.purple[2] + "A0",
    "editorOverviewRuler.findMatchForeground": colors.yellow[0] + "80",
    "editorOverviewRuler.rangeHighlightForeground": colors.blue[0] + "80",
    "editorOverviewRuler.selectionHighlightForeground": colors.purple[0] + "80",
    "editorOverviewRuler.wordHighlightForeground": colors.magenta[0] + "80",
    "editorOverviewRuler.wordHighlightStrongForeground": colors.magenta[0] + "A0",
    "editorOverviewRuler.wordHighlightTextForeground": colors.magenta[0] + "80",
    "editorRuler.foreground": colors.ink[1],
    "editor.stackFrameHighlightBackground": colors.yellow[1] + "30",
    "editor.focusedStackFrameHighlightBackground": colors.yellow[2] + "30",
    "editorStickyScrollHover.background": colors.glow[0],
    "editorSuggestWidget.background": colors.canvas[1],
    "editorSuggestWidget.border": colors.canvas[4],
    "editorSuggestWidget.foreground": colors.ink[2],
    "editorSuggestWidget.highlightForeground": colors.purple[1],
    "editorSuggestWidget.selectedBackground": colors.glow[0],
    "editorWhitespace.foreground": colors.ink[0],
    "editorWidget.background": colors.canvas[1],
    "editorWidget.border": colors.canvas[4],
    "editorWidget.foreground": colors.ink[2],
    "editorWidget.resizeBorder": colors.pink[1],
    "editorLightBulb.foreground": colors.yellow[1],
    "editorError.foreground": colors.orange[1],
    "editorError.border": "#00000000",
    "editorError.background": "#00000000",
    "editorWarning.foreground": colors.yellow[1],
    "editorWarning.border": "#00000000",
    "editorWarning.background": "#00000000",
    "editorInfo.foreground": colors.blue[1],
    "editorInfo.border": "#00000000",
    "editorInfo.background": "#00000000",
    "problemsErrorIcon.foreground": colors.orange[1],
    "problemsInfoIcon.foreground": colors.blue[1],
    "problemsWarningIcon.foreground": colors.yellow[1],
    "extensionButton.prominentForeground": colors.canvas[0],
    "extensionButton.prominentBackground": colors.purple[1],
    "extensionButton.separator": colors.canvas[0],
    "extensionButton.prominentHoverBackground": colors.purple[2],
    "extensionBadge.remoteBackground": colors.blue[1],
    "extensionBadge.remoteForeground": colors.canvas[0],
    "extensionIcon.starForeground": colors.yellow[1],
    "extensionIcon.verifiedForeground": colors.green[1],
    "extensionIcon.preReleaseForeground": colors.ink[1],
    "extensionIcon.sponsorForeground": colors.pink[1],
    "gitDecoration.addedResourceForeground": colors.green[1],
    "gitDecoration.conflictingResourceForeground": colors.magenta[1],
    "gitDecoration.deletedResourceForeground": colors.pink[1],
    "gitDecoration.ignoredResourceForeground": colors.ink[0],
    "gitDecoration.modifiedResourceForeground": colors.purple[1],
    "gitDecoration.stageDeletedResourceForeground": colors.pink[1],
    "gitDecoration.stageModifiedResourceForeground": colors.yellow[1],
    "gitDecoration.submoduleResourceForeground": colors.magenta[1],
    "gitDecoration.untrackedResourceForeground": colors.green[1],
    "scmGraph.historyItemRefColor": colors.blue[1],
    "scmGraph.historyItemBaseRefColor": colors.pink[1],
    "scmGraph.historyItemRemoteRefColor": colors.magenta[1],
    "scmGraph.foreground1": colors.yellow[1],
    "scmGraph.foreground2": colors.pink[1],
    "scmGraph.foreground3": colors.orange[1],
    "scmGraph.foreground4": colors.green[1],
    "scmGraph.foreground5": colors.magenta[1],
    "input.background": colors.canvas[0],
    "input.border": colors.canvas[4],
    "input.foreground": colors.ink[3],
    "input.placeholderForeground": colors.ink[1],
    "inputOption.hoverBackground": colors.glow[1],
    "inputOption.activeBackground": colors.glow[2],
    "inputOption.activeBorder": colors.purple[1],
    "inputOption.activeForeground": colors.ink[3],
    "inputValidation.errorBackground": colors.orange[1],
    "inputValidation.errorBorder": colors.orange[2],
    "inputValidation.errorForeground": colors.canvas[0],
    "inputValidation.infoBackground": colors.blue[1],
    "inputValidation.infoBorder": colors.blue[2],
    "inputValidation.infoForeground": colors.canvas[0],
    "inputValidation.warningBackground": colors.yellow[1],
    "inputValidation.warningBorder": colors.yellow[2],
    "inputValidation.warningForeground": colors.canvas[0],
    "list.activeSelectionBackground": colors.glow[3],
    "list.activeSelectionForeground": colors.ink[3],
    "list.deemphasizedForeground": colors.ink[1],
    "list.dropBackground": colors.purple[1] + "30",
    "list.focusBackground": colors.glow[1],
    "list.focusForeground": colors.ink[3],
    "list.focusHighlightForeground": colors.purple[1],
    "list.focusOutline": "#00000000",
    "list.highlightForeground": colors.purple[1],
    "list.hoverBackground": colors.glow[1],
    "list.hoverForeground": colors.ink[3],
    "list.inactiveSelectionBackground": colors.glow[0],
    "list.inactiveSelectionForeground": colors.ink[3],
    "list.activeSelectionIconForeground": colors.purple[1],
    "list.warningForeground": colors.yellow[1],
    "list.errorForeground": colors.orange[1],
    "listFilterWidget.background": colors.canvas[0],
    "listFilterWidget.noMatchesOutline": colors.yellow[1],
    "listFilterWidget.outline": "#00000000",
    "tree.indentGuidesStroke": colors.glow[4],
    "tree.inactiveIndentGuidesStroke": colors.glow[2],
    "tree.tableColumnsBorder": colors.canvas[3],
    "tree.tableOddRowsBackground": colors.glow[0],
    "menu.background": colors.canvas[1],
    "menu.border": colors.canvas[4],
    "menu.foreground": colors.ink[2],
    "menu.selectionBackground": colors.glow[1],
    "menu.selectionBorder": "#00000000",
    "menu.selectionForeground": colors.ink[3],
    "menu.separatorBackground": colors.canvas[3],
    "menubar.selectionBackground": colors.glow[3],
    "menubar.selectionForeground": colors.ink[3],
    "menubar.selectionBorder": "#00000000",
    "merge.border": colors.canvas[2],
    "merge.commonContentBackground": colors.glow[0],
    "merge.commonHeaderBackground": colors.glow[1],
    "merge.currentContentBackground": colors.cyan[1] + "30",
    "merge.currentHeaderBackground": colors.cyan[1] + "60",
    "merge.incomingContentBackground": colors.magenta[1] + "30",
    "merge.incomingHeaderBackground": colors.magenta[1] + "60",
    "minimap.background": "#00000000",
    "minimap.chatEditHighlight": colors.cyan[1] + "80",
    "minimap.findMatchHighlight": colors.yellow[0] + "80",
    "minimap.selectionHighlight": colors.purple[0] + "80",
    "minimap.selectionOccurrenceHighlight": colors.magenta[0] + "80",
    "minimap.warningHighlight": colors.yellow[1],
    "minimap.errorHighlight": colors.orange[1],
    "minimapSlider.background": colors.glow[0],
    "minimapSlider.hoverBackground": colors.glow[1],
    "minimapSlider.activeBackground": colors.glow[2],
    "minimapGutter.addedBackground": colors.green[1],
    "minimapGutter.deletedBackground": colors.pink[1],
    "minimapGutter.modifiedBackground": colors.purple[1],
    "notificationCenter.border": colors.purple[1],
    "notificationCenterHeader.foreground": colors.ink[3],
    "notificationCenterHeader.background": colors.canvas[1],
    "notificationToast.border": colors.purple[1],
    "notifications.foreground": colors.ink[3],
    "notifications.background": colors.canvas[1],
    "notifications.border": colors.purple[1],
    "notificationLink.foreground": colors.blue[1],
    "notificationsErrorIcon.foreground": colors.orange[1],
    "notificationsWarningIcon.foreground": colors.yellow[1],
    "notificationsInfoIcon.foreground": colors.blue[1],
    "panel.background": colors.canvas[0],
    "panel.border": colors.canvas[3],
    "panelSection.border": colors.canvas[2],
    "panelSection.dropBackground": colors.purple[1] + "30",
    "panelTitle.activeBorder": colors.purple[1],
    "panelTitle.activeForeground": colors.ink[3],
    "panelTitle.inactiveForeground": colors.ink[2],
    "peekView.border": colors.purple[1],
    "peekViewEditor.background": colors.canvas[1],
    "peekViewEditorGutter.background": colors.canvas[1],
    "peekViewEditor.matchHighlightBackground": colors.cyan[1] + "30",
    "peekViewEditor.matchHighlightBorder": "#00000000",
    "peekViewResult.background": colors.canvas[1],
    "peekViewResult.fileForeground": colors.ink[3],
    "peekViewResult.lineForeground": colors.ink[3],
    "peekViewResult.matchHighlightBackground": colors.cyan[1] + "30",
    "peekViewResult.selectionBackground": colors.glow[0],
    "peekViewResult.selectionForeground": colors.ink[3],
    "peekViewTitle.background": colors.canvas[0],
    "peekViewTitleDescription.foreground": "#bac2deb3",
    "peekViewTitleLabel.foreground": colors.ink[3],
    "pickerGroup.border": colors.purple[1],
    "pickerGroup.foreground": colors.purple[1],
    "progressBar.background": colors.purple[1],
    "scrollbar.background": "#00000000",
    "scrollbar.shadow": "#00000030",
    "scrollbarSlider.activeBackground": colors.glow[3],
    "scrollbarSlider.background": colors.glow[1],
    "scrollbarSlider.hoverBackground": colors.glow[2],
    "settings.focusedRowBackground": "#00000000",
    "settings.focusedRowBorder": "#00000000",
    "settings.headerForeground": colors.ink[3],
    "settings.modifiedItemIndicator": colors.purple[1],
    "settings.rowHoverBackground": "#00000000",
    "sideBar.background": colors.canvas[1],
    "sideBar.dropBackground": colors.purple[1] + "30",
    "sideBar.foreground": colors.ink[2],
    "sideBar.border": "#00000000",
    "sideBarSectionHeader.background": colors.canvas[1],
    "sideBarSectionHeader.border": colors.canvas[3],
    "sideBarSectionHeader.foreground": colors.ink[3],
    "sideBarTitle.foreground": colors.purple[1],
    "banner.background": colors.glow[0],
    "banner.foreground": colors.ink[3],
    "banner.iconForeground": colors.ink[3],
    "statusBar.background": colors.canvas[2],
    "statusBar.foreground": colors.ink[2],
    "statusBar.border": "#00000000",
    "statusBar.noFolderBackground": colors.canvas[2],
    "statusBar.noFolderForeground": colors.ink[2],
    "statusBar.noFolderBorder": "#00000000",
    "statusBar.debuggingBackground": colors.pink[1],
    "statusBar.debuggingForeground": colors.canvas[0],
    "statusBar.debuggingBorder": "#00000000",
    "statusBarItem.remoteBackground": colors.blue[1],
    "statusBarItem.remoteForeground": colors.canvas[0],
    "statusBarItem.activeBackground": colors.glow[2],
    "statusBarItem.hoverBackground": colors.glow[1],
    "statusBarItem.hoverForeground": colors.ink[3],
    "statusBarItem.prominentForeground": colors.purple[1],
    "statusBarItem.prominentBackground": "#00000000",
    "statusBarItem.prominentHoverBackground": colors.glow[1],
    "statusBarItem.prominentHoverForeground": colors.purple[2],
    "statusBarItem.errorForeground": colors.orange[1],
    "statusBarItem.errorBackground": "#00000000",
    "statusBarItem.warningForeground": colors.yellow[1],
    "statusBarItem.warningBackground": "#00000000",
    "commandCenter.foreground": colors.ink[2],
    "commandCenter.inactiveForeground": colors.ink[1],
    "commandCenter.activeForeground": colors.purple[1],
    "commandCenter.background": colors.canvas[1],
    "commandCenter.activeBackground": colors.glow[1],
    "commandCenter.border": colors.canvas[3],
    "commandCenter.inactiveBorder": colors.canvas[2],
    "commandCenter.activeBorder": colors.purple[1],
    "tab.activeBackground": colors.canvas[0],
    "tab.activeBorder": "#00000000",
    "tab.activeBorderTop": colors.purple[1],
    "tab.activeForeground": colors.purple[1],
    "tab.activeModifiedBorder": colors.yellow[1],
    "tab.border": "#00000000",
    "tab.hoverBackground": colors.canvas[2],
    "tab.hoverBorder": "#00000000",
    "tab.hoverForeground": colors.ink[3],
    "tab.inactiveBackground": colors.canvas[1],
    "tab.inactiveForeground": colors.ink[2],
    "tab.inactiveModifiedBorder": colors.yellow[2],
    "tab.lastPinnedBorder": colors.purple[1],
    "tab.unfocusedActiveBackground": colors.canvas[1],
    "tab.unfocusedActiveBorder": "#00000000",
    "tab.unfocusedActiveBorderTop": colors.purple[0],
    "tab.unfocusedInactiveBackground": colors.canvas[0],
    "terminal.foreground": colors.ink[3],
    "terminal.ansiBlack": colors.canvas[1],
    "terminal.ansiRed": colors.orange[1],
    "terminal.ansiGreen": colors.green[1],
    "terminal.ansiYellow": colors.yellow[1],
    "terminal.ansiBlue": colors.blue[1],
    "terminal.ansiMagenta": colors.magenta[1],
    "terminal.ansiCyan": colors.cyan[1],
    "terminal.ansiWhite": colors.ink[2],
    "terminal.ansiBrightBlack": colors.canvas[2],
    "terminal.ansiBrightRed": colors.orange[2],
    "terminal.ansiBrightGreen": colors.green[2],
    "terminal.ansiBrightYellow": colors.yellow[2],
    "terminal.ansiBrightBlue": colors.blue[2],
    "terminal.ansiBrightMagenta": colors.magenta[2],
    "terminal.ansiBrightCyan": colors.cyan[2],
    "terminal.ansiBrightWhite": colors.ink[3],
    "terminal.selectionBackground": colors.purple[0] + "C0",
    "terminal.inactiveSelectionBackground": colors.purple[0] + "80",
    "terminalCursor.background": colors.canvas[0],
    "terminalCursor.foreground": colors.purple[2],
    "terminal.border": colors.canvas[3],
    "terminal.dropBackground": colors.purple[1] + "30",
    "terminal.tab.activeBorder": colors.purple[1],
    "terminalCommandDecoration.defaultBackground": colors.purple[1],
    "terminalCommandDecoration.successBackground": colors.green[1],
    "terminalCommandDecoration.errorBackground": colors.orange[1],
    "titleBar.activeBackground": colors.canvas[2],
    "titleBar.activeForeground": colors.ink[2],
    "titleBar.inactiveBackground": colors.canvas[2],
    "titleBar.inactiveForeground": colors.ink[1],
    "titleBar.border": "#00000000",
    "toolbar.hoverBackground": colors.glow[1],
    "toolbar.activeBackground": colors.glow[2],
    "welcomePage.tileBackground": colors.canvas[1],
    "welcomePage.progress.background": colors.canvas[0],
    "welcomePage.progress.foreground": colors.purple[1],
    "walkThrough.embeddedEditorBackground": colors.canvas[0],
    "symbolIcon.textForeground": colors.ink[2],
    "symbolIcon.arrayForeground": colors.pink[1],
    "symbolIcon.booleanForeground": colors.orange[1],
    "symbolIcon.classForeground": colors.yellow[1],
    "symbolIcon.colorForeground": colors.orange[1],
    "symbolIcon.constantForeground": colors.orange[1],
    "symbolIcon.constructorForeground": colors.blue[2],
    "symbolIcon.enumeratorForeground": colors.yellow[1],
    "symbolIcon.enumeratorMemberForeground": colors.purple[1],
    "symbolIcon.eventForeground": colors.blue[1],
    "symbolIcon.fieldForeground": colors.purple[1],
    "symbolIcon.fileForeground": colors.magenta[1],
    "symbolIcon.folderForeground": colors.yellow[1],
    "symbolIcon.functionForeground": colors.blue[1],
    "symbolIcon.interfaceForeground": colors.yellow[1],
    "symbolIcon.keyForeground": colors.purple[1],
    "symbolIcon.keywordForeground": colors.magenta[1],
    "symbolIcon.methodForeground": colors.blue[1],
    "symbolIcon.moduleForeground": colors.magenta[1],
    "symbolIcon.namespaceForeground": colors.green[1],
    "symbolIcon.nullForeground": colors.orange[1],
    "symbolIcon.numberForeground": colors.orange[1],
    "symbolIcon.objectForeground": colors.pink[1],
    "symbolIcon.operatorForeground": colors.cyan[1],
    "symbolIcon.packageForeground": colors.green[1],
    "symbolIcon.propertyForeground": colors.purple[1],
    "symbolIcon.referenceForeground": colors.cyan[1],
    "symbolIcon.snippetForeground": colors.green[1],
    "symbolIcon.stringForeground": colors.green[1],
    "symbolIcon.structForeground": colors.orange[1],
    "symbolIcon.typeParameterForeground": colors.cyan[1],
    "symbolIcon.unitForeground": colors.orange[1],
    "symbolIcon.variableForeground": colors.pink[1],
    "charts.foreground": colors.ink[2],
    "charts.lines": colors.glow[4],
    "charts.red": colors.pink[1],
    "charts.blue": colors.blue[1],
    "charts.yellow": colors.yellow[1],
    "charts.orange": colors.orange[1],
    "charts.green": colors.green[1],
    "charts.purple": colors.purple[1],
    "errorLens.errorBackground": colors.orange[0] + "30",
    "errorLens.errorBackgroundLight": colors.orange[0] + "30",
    "errorLens.errorForeground": colors.orange[1],
    "errorLens.errorForegroundLight": colors.orange[2],
    "errorLens.errorMessageBackground": colors.orange[0] + "30",
    "errorLens.hintBackground": colors.green[0] + "30",
    "errorLens.hintBackgroundLight": colors.green[0] + "30",
    "errorLens.hintForeground": colors.green[1],
    "errorLens.hintForegroundLight": colors.green[2],
    "errorLens.hintMessageBackground": colors.green[0] + "30",
    "errorLens.infoBackground": colors.blue[0] + "30",
    "errorLens.infoBackgroundLight": colors.blue[0] + "30",
    "errorLens.infoForeground": colors.blue[1],
    "errorLens.infoForegroundLight": colors.blue[2],
    "errorLens.infoMessageBackground": colors.blue[0] + "30",
    "errorLens.statusBarErrorForeground": colors.orange[1],
    "errorLens.statusBarHintForeground": colors.green[1],
    "errorLens.statusBarIconErrorForeground": colors.orange[1],
    "errorLens.statusBarIconWarningForeground": colors.yellow[1],
    "errorLens.statusBarInfoForeground": colors.blue[1],
    "errorLens.statusBarWarningForeground": colors.yellow[1],
    "errorLens.warningBackground": colors.yellow[0] + "30",
    "errorLens.warningBackgroundLight": colors.yellow[0] + "30",
    "errorLens.warningForeground": colors.yellow[1],
    "errorLens.warningForegroundLight": colors.yellow[2],
    "errorLens.warningMessageBackground": colors.yellow[0] + "30",
    "issues.closed": colors.purple[1],
    "issues.newIssueDecoration": colors.yellow[1],
    "issues.open": colors.green[1],
    "pullRequests.closed": colors.pink[1],
    "pullRequests.draft": colors.ink[1],
    "pullRequests.merged": colors.purple[1],
    "pullRequests.notification": colors.blue[1],
    "pullRequests.open": colors.green[1],
    "editorBracketHighlight.foreground1": colors.magenta[0],
    "editorBracketHighlight.foreground2": colors.purple[0],
    "editorBracketHighlight.foreground3": colors.blue[0],
    "editorBracketHighlight.foreground4": colors.cyan[0],
    "editorBracketHighlight.foreground5": colors.green[0],
    "editorBracketHighlight.foreground6": colors.yellow[0],
    "editorBracketPairGuide.background1": colors.magenta[0] + "80",
    "editorBracketPairGuide.background2": colors.purple[0] + "80",
    "editorBracketPairGuide.background3": colors.blue[0] + "80",
    "editorBracketPairGuide.background4": colors.cyan[0] + "80",
    "editorBracketPairGuide.background5": colors.green[0] + "80",
    "editorBracketPairGuide.background6": colors.yellow[0] + "80",
    "editorBracketPairGuide.activeBackground1": colors.magenta[0],
    "editorBracketPairGuide.activeBackground2": colors.purple[0],
    "editorBracketPairGuide.activeBackground3": colors.blue[0],
    "editorBracketPairGuide.activeBackground4": colors.cyan[0],
    "editorBracketPairGuide.activeBackground5": colors.green[0],
    "editorBracketPairGuide.activeBackground6": colors.yellow[0],
    "editorBracketHighlight.unexpectedBracket.foreground": colors.orange[2],
    "table.headerBackground": colors.glow[0],
    "table.headerForeground": colors.ink[3],
    // "debugTokenExpression.number": colors.pink[1],
    // "debugTokenExpression.boolean": colors.magenta[1],
    // "debugTokenExpression.string": colors.green[1],
    // "debugTokenExpression.error": colors.orange[1],
    // "debugIcon.breakpointForeground": colors.orange[1],
    // "debugIcon.breakpointDisabledForeground": "#f38ba899",
    // "debugIcon.breakpointUnverifiedForeground": "#a6738c",
    // "debugIcon.breakpointCurrentStackframeForeground": colors.canvas[3],
    // "debugIcon.breakpointStackframeForeground": colors.canvas[3],
    // "debugIcon.startForeground": colors.green[1],
    // "debugIcon.pauseForeground": colors.blue[1],
    // "debugIcon.stopForeground": colors.orange[1],
    // "debugIcon.disconnectForeground": colors.canvas[3],
    // "debugIcon.restartForeground": colors.cyan[1],
    // "debugIcon.stepOverForeground": colors.purple[1],
    // "debugIcon.stepIntoForeground": colors.ink[3],
    // "debugIcon.stepOutForeground": colors.ink[3],
    // "debugIcon.continueForeground": colors.green[1],
    // "debugIcon.stepBackForeground": colors.canvas[3],
    // "debugConsole.infoForeground": colors.blue[1],
    // "debugConsole.warningForeground": colors.orange[1],
    // "debugConsole.errorForeground": colors.orange[1],
    // "debugConsole.sourceForeground": colors.yellow[2],
    // "debugConsoleInputIcon.foreground": colors.ink[3],
    // "testing.runAction": colors.purple[1],
    // "testing.iconErrored": colors.orange[1],
    // "testing.iconFailed": colors.orange[1],
    // "testing.iconPassed": colors.green[1],
    // "testing.iconQueued": colors.blue[1],
    // "testing.iconUnset": colors.ink[2],
    // "testing.iconSkipped": colors.ink[0],
    // "testing.iconErrored.retired": colors.orange[1],
    // "testing.iconFailed.retired": colors.orange[1],
    // "testing.iconPassed.retired": colors.green[1],
    // "testing.iconQueued.retired": colors.blue[1],
    // "testing.iconUnset.retired": colors.ink[3],
    // "testing.iconSkipped.retired": colors.ink[0],
    // "testing.peekBorder": colors.purple[1],
    // "testing.peekHeaderBackground": colors.canvas[2],
    // "testing.message.error.lineBackground": "#f38ba826",
    // "testing.message.info.decorationForeground": "#a6e3a1cc",
    // "testing.message.info.lineBackground": "#a6e3a126",
    // "testing.messagePeekBorder": colors.purple[1],
    // "testing.messagePeekHeaderBackground": colors.canvas[3],
    // "testing.coveredBackground": "#a6e3a14d",
    // "testing.coveredBorder": "#00000000",
    // "testing.coveredGutterBackground": "#a6e3a14d",
    // "testing.uncoveredBranchBackground": "#f38ba833",
    // "testing.uncoveredBackground": "#f38ba833",
    // "testing.uncoveredBorder": "#00000000",
    // "testing.uncoveredGutterBackground": "#f38ba840",
    // "testing.coverCountBadgeBackground": "#00000000",
    // "testing.coverCountBadgeForeground": colors.purple[1],
  },
  semanticHighlighting: true,
  semanticTokenColors: {
    builtinAttribute: colors.purple[1],
    generic: colors.orange[1],
    tomlTableKey: colors.pink[1],
    deriveHelper: colors.cyan[1],
  },
  tokenColors: [
    {
      scope: ["comment", "punctuation.definition.comment", "string.comment"],
      settings: { foreground: colors.ink[1], fontStyle: "italic" },
    },
    {
      scope: [
        "punctuation.definition.dictionary",
        "punctuation.definition.table",
        "punctuation.definition.array",
        "punctuation.definition.sequence",
        "punctuation.definition.binding-pattern",
        "punctuation.brackets.square",
        "punctuation.definition.begin.bracket.square",
        "punctuation.definition.end.bracket.square",
        "punctuation.squarebracket",
        "meta.brace.square",
      ],
      settings: { foreground: colors.pink[0] },
    },
    {
      scope: [
        "punctuation.definition.keyword",
        "punctuation.definition.block",
        "punctuation.brackets.curly",
        "punctuation.definition.begin.bracket.curly",
        "punctuation.definition.end.bracket.curly",
        "punctuation.curlybrace",
        "punctuation.section",
        "meta.brace.curly",
      ],
      settings: { foreground: colors.magenta[0] },
    },
    {
      scope: [
        "punctuation.semi",
        "punctuation.comma",
        "punctuation.eq",
        "punctuation.separator",
        "punctuation.terminator",
        "punctuation.accessor",
        "punctuation.definition.attribute",
        "punctuation.definition.tag",
        "punctuation.brackets.attribute",
        "punctuation.section.property-list",
        "punctuation.other",
        "keyword.operator.access",
        "keyword.operator.namespace",
        "keyword.operator.key-value",
        "keyword.operator.rest",
      ],
      settings: { foreground: colors.purple[0] },
    },
    {
      scope: [
        "punctuation.definition.parameters",
        "punctuation.brackets.round",
        "punctuation.definition.begin.bracket.round",
        "punctuation.definition.end.bracket.round",
        "punctuation.section.function",
        "punctuation.definition.arguments",
        "punctuation.parenthesis",
        "meta.brace.round",
      ],
      settings: { foreground: colors.blue[0] },
    },
    {
      scope: [
        "punctuation.definition.string",
        "punctuation.definition.lifetime",
        "punctuation.definition.link",
        "punctuation.definition.metadata",
        "punctuation.definition.raw",
      ],
      settings: { foreground: colors.green[0] },
    },
    {
      scope: [
        "punctuation.definition.template-expression",
        "punctuation.definition.interpolation",
        "punctuation.section.embedded",
      ],
      settings: { foreground: colors.cyan[0] },
    },
    {
      scope: [
        "keyword.operator.type",
        "keyword.operator.optional",
        "keyword.operator.definiteassignment",
        "punctuation.definition.typeparameters",
        "punctuation.definition.entity",
        "punctuation.brackets.angle",
        "punctuation.definition.bold",
      ],
      settings: { foreground: colors.orange[0] },
    },
    {
      scope: [
        "keyword.control",
        "keyword.modifier",
        "keyword.other",
        "keyword.operator.ternary",
        "keyword.operator.arrow",
        "keyword.operator.quantifier",
        "keyword.var",
        "keyword.function",
        "keyword.package",
        "punctuation.definition.group",
        "storage.type",
        "storage.modifier",
        "fenced_code.block.language",
      ],
      settings: { foreground: colors.magenta[1] },
    },
    {
      scope: [
        "variable.language",
        "keyword.operator.assignment",
        "keyword.operator.comparison",
        "keyword.operator.relational",
        "keyword.operator.logical",
        "keyword.operator.math",
        "keyword.operator.arithmetic",
        "keyword.operator.expression",
        "keyword.operator.typeof",
        "keyword.operator.new",
        "keyword.operator.borrow",
        "keyword.operator.dereference",
        "keyword.operator.address",
        "keyword.operator.string",
        "keyword.operator.range",
        "keyword.operator.spread",
        "keyword.operator.increment-decrement",
        "keyword.operator.increment",
        "keyword.operator.decrement",
        "keyword.operator.question",
        "keyword.operator.class",
        "keyword.operator.pattern",
        "keyword.operator.redirect",
        "keyword.operator.existential",
        "keyword.operator.or",
        "punctuation.definition.logical-expression",
        "keyword.generator",
        "string.other.link",
      ],
      settings: { foreground: colors.cyan[1] },
    },
    {
      scope: [
        "function",
        "entity.name.function",
        "entity.name.function.macro",
        "entity.name.tag",
        "meta.link",
        "support.function",
        "punctuation.definition.list",
      ],
      settings: { foreground: colors.blue[1] },
    },
    {
      scope: [
        "variable",
        "entity.name.variable",
        "entity.other.attribute-name.id",
        "entity.other.attribute-name.pseudo-element",
      ],
      settings: { foreground: colors.pink[1] },
    },
    {
      scope: [
        "constant.numeric",
        "constant.language",
        "constant.other",
        "support.constant",
        "support.variable",
        "support.type.builtin",
        "variable.other.enummember",
        "entity.name.type.parameter",
        "entity.other.attribute-name.pseudo-class",
      ],
      settings: { foreground: colors.orange[1] },
    },
    {
      scope: [
        "meta.object-literal.key",
        "meta.property-name",
        "entity.other.attribute-name",
        "entity.name.namespace",
        "entity.name.variable.field",
        "variable.object.property",
        "variable.other.property",
        "variable.other.object.property",
        "variable.other.readwrite.alias",
        "support.type.property-name",
        "constant.language.null",
        "constant.language.undefined",
        "punctuation.definition.quote",
      ],
      settings: { foreground: colors.purple[1] },
    },
    {
      scope: [
        "string",
        "source.regexp",
        "string.regexp",
        "entity.name.type.lifetime",
        "storage.modifier.lifetime",
        "markup.inline",
        "markup.fenced_code",
      ],
      settings: { foreground: colors.green[1] },
    },
    {
      scope: [
        "support.type.primitive",
        "support.class",
        "keyword.type",
        "entity.name.type",
        "entity.name.class",
        "entity.name.section",
        "entity.name.module",
        "entity.other.attribute-name.class",
        "entity.other.inherited-class",
        "constant.character",
        "constant.other.character-class.range",
        "keyword.other.unit",
        "markup.heading",
      ],
      settings: { foreground: colors.yellow[1] },
    },
    {
      scope: ["markup.italic"],
      settings: { foreground: colors.purple[1], fontStyle: "italic" },
    },
    {
      scope: ["markup.bold"],
      settings: { foreground: colors.orange[1], fontStyle: "bold" },
    },
    {
      scope: ["markup.strikethrough"],
      settings: { foreground: colors.pink[1], fontStyle: "strikethrough" },
    },
    {
      scope: "invalid",
      settings: { fontStyle: "bold", foreground: colors.orange[2] },
    },
    {
      scope: "source.json meta.structure.dictionary.json support.type.property-name.json",
      settings: {
        foreground: colors.magenta[1],
      },
    },
    {
      scope:
        "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      settings: {
        foreground: colors.purple[1],
      },
    },
    {
      scope:
        "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      settings: {
        foreground: colors.blue[1],
      },
    },
    {
      scope:
        "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      settings: {
        foreground: colors.cyan[1],
      },
    },
    {
      scope:
        "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
      settings: {
        foreground: colors.pink[1],
      },
    },
  ],
};
